[build]
  command = "npm run build"
  publish = ".output/public"
  functions = ".output/server"

[dev]
  command = "npm run dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200