[build]
  command = "npx nuxi build"
  publish = ".output/public"
  environment = { NUXT_TELEMETRY_DISABLED = "1" }

[functions]
  node_bundler = "esbuild"

[cache]
  paths = ["node_modules", ".output"]

  [[redirects]]
  from = "/old-url"
  to = "/new-url"
  status = 301