name = "cms-whiteboston" 
account_id = "${CLOUDFLARE_ACCOUNT_ID}"

main = "src/index.js"
compatibility_date = "2024-12-12"

[[d1_databases]]
binding = "DB"
database_name = "${D1_DATABASE_NAME}"
database_id = "${D1_DATABASE_ID}"
preview_database_id = "DB"