name = "cms-whiteboston" 
#account_id = "${CLOUDFLARE_ACCOUNT_ID}"

main = "src/index.js"
compatibility_date = "2024-12-12"

[[d1_databases]]
binding = "DB"
database_name = "cms-whiteboston"
database_id = "5db34b16-0be0-4ebb-ad72-ea9028b74eff"
preview_database_id = "DB"